apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploymnt-pods
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
     containers:
       - name: nginx-c1
         image: nginx
         ports:
          - containerPort: 80

